---
# tasks file for docker-rabbitmq

- include: debian.yml
  when: ansible_os_family == 'Debian'

#- include: redhat.yml
#  when: ansible_os_family == 'RedHat'

- name: Clone rabbitmq repo
  hg:
    repo: https://nickball@bitbucket.org/nickball/docker-rabbitmq
    dest: /opt/rabbitmq
    revision: default
    force: no
    purge: no
  sudo: yes
